### ISSUE TITLE
Figure out LLVM integration regresson

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/sdxl-scripts#22]
We discovered a regression in SDXL and began bisecting the commits between May 15 and May 30. The bisect identified that a commit (https://github.com/iree-org/iree/pull/17459) involving LLVM integration was the cause.

During the second round of bisecting in the LLVM, we confirmed that this particular commit caused the issue (https://github.com/shark-infra/llvm-project/commit/8e8d2595dafa230a3da7f410200d89f05b6e8d87).

This is the result when the head just before the suspected commit above:
(https://github.com/shark-infra/llvm-project/commit/2217d1706a76d3f298899f824354ca9d96c45813)
```
Load Average: 0.42, 0.56, 6.95
***WARNING*** CPU scaling is enabled; the benchmark real-time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
BM_main/process_time/real_time              62.5 ms         63.8 ms           11 items_per_second=15.9964/s
BM_main/process_time/real_time              62.7 ms         63.9 ms           11 items_per_second=15.9582/s
BM_main/process_time/real_time              62.9 ms         64.2 ms           11 items_per_second=15.9037/s
BM_main/process_time/real_time_mean         62.7 ms         64.0 ms            3 items_per_second=15.9528/s
BM_main/process_time/real_time_median       62.7 ms         63.9 ms            3 items_per_second=15.9582/s
BM_main/process_time/real_time_stddev      0.183 ms        0.233 ms            3 items_per_second=0.0465725/s
BM_main/process_time/real_time_cv           0.29 %          0.36 %             3 items_per_second=0.29%
```

This is the result when the head just on the suspected commit above:
https://github.com/shark-infra/llvm-project/commit/8e8d2595dafa230a3da7f410200d89f05b6e8d87
```
Load Average: 0.56, 0.58, 6.78
***WARNING*** CPU scaling is enabled; the benchmark real-time measurements may be noisy and will incur extra overhead.
***WARNING*** Library was built as DEBUG. Timings may be affected.
------------------------------------------------------------------------------------------------
Benchmark                                      Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------------------
BM_main/process_time/real_time              63.2 ms         64.5 ms           11 items_per_second=15.8121/s
BM_main/process_time/real_time              63.5 ms         64.8 ms           11 items_per_second=15.7461/s
BM_main/process_time/real_time              63.6 ms         64.8 ms           11 items_per_second=15.7327/s
BM_main/process_time/real_time_mean         63.4 ms         64.7 ms            3 items_per_second=15.7636/s
BM_main/process_time/real_time_median       63.5 ms         64.8 ms            3 items_per_second=15.7461/s
BM_main/process_time/real_time_stddev      0.171 ms        0.200 ms            3 items_per_second=0.0424904/s
BM_main/process_time/real_time_cv           0.27 %          0.31 %             3 items_per_second=0.27%
```
I also got the Tracy captures. Each dispatch had been affected at some level. 
Before the Regression (Head is at 2217d1706a76d3f298899f824354ca9d96c45813) 
<img width="716" alt="unet-2217-Validate" src="https://github.com/nod-ai/sdxl-scripts/assets/99776114/1d2c87c3-6d91-499c-ad9b-bfc7b2b2d120">
After the Regression (Head is at  8e8d2595dafa230a3da7f410200d89f05b6e8d87) 
<img width="706" alt="unet-8e8d-Validate" src="https://github.com/nod-ai/sdxl-scripts/assets/99776114/c4ebad00-621d-4fe2-ab9b-e165c65142c4">

However, when we revert that causing commit (8e8d2595dafa230a3da7f410200d89f05b6e8d87) from LLVM, we do not see improvement on the TOM.
![Screenshot_2024-06-05_001534](https://github.com/nod-ai/sdxl-scripts/assets/99776114/34eef248-a332-49e9-9736-81717647cc6f)
1-> unet-revert-8e8d259.vmfb (The branch that Mahesh prepared)
2-> unet-TOM.vmfb
3-> unet-2217-Validate.vmfb (This is the one where we have improvement)
4-> unet-8e8d-Validate.vmfb 
I run everything on  GPU 5.
CC: @MaheshRavishankar @antiagainst

**Comment by erman-gurses** [comment]
I added the details about the issue above.

**Comment by antiagainst** [comment]
Thanks @erman-gurses!
