### ISSUE TITLE
[kernel] Plumb through int8 mfma support

### ISSUE THREAD

**Issue by antiagainst** [nod-ai/sdxl-scripts#28]
Adding support for the following mfma instrinsics and tests:

```
    v_mfma_i32_32x32x16_i8
    v_mfma_i32_16x16x32_i8
```

there are also blocked versions:

```
    v_mfma_i32_32x32x4_2b_i8
    v_mfma_i32_16x16x4_4b_i8
    v_mfma_i32_4x4x4_16b_i8
```

but we can worry about those later.

**Comment by aviator19941** [comment]
iree branch: https://github.com/iree-org/iree/tree/shared/sdxl_quantized
punet_06_19_all_signed.mlir: https://gist.github.com/aviator19941/7e2396d3aa8b4f26773c4296cf620a95
punet_06_19.irpa: https://sharkpublic.blob.core.windows.net/sharkpublic/avi/punet_06_19.irpa

`
iree-compile punet_06_19_all_signed.mlir --iree-global-opt-propagate-transposes=true --iree-opt-const-eval=false --iree-opt-outer-dim-concat=true --iree-vm-target-truncate-unsupported-floats --iree-llvmgpu-enable-prefetch=true --iree-opt-data-tiling=false --iree-codegen-gpu-native-math-precision=true --iree-rocm-waves-per-eu=2 --iree-flow-inline-constants-max-byte-length=1 --iree-preprocessing-pass-pipeline="builtin.module(iree-preprocessing-transpose-convolution-pipeline, util.func(iree-preprocessing-pad-to-intrinsics))" --iree-flow-enable-aggressive-fusion --iree-global-opt-enable-fuse-horizontal-contractions=true --iree-opt-aggressively-propagate-transposes=true --iree-codegen-llvmgpu-use-vector-distribution=true --iree-hal-target-backends=rocm --iree-rocm-target-chip=gfx942 --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-codegen-transform-dialect-library="spec.mlir" -o punet_06_24_all_signed.vmfb
`

**Comment by raikonenfnu** [comment]
I have a tested and numerically correct WIP here https://github.com/iree-org/iree/tree/shared/int8mfma

Using initial IR from: https://gist.github.com/raikonenfnu/99ca5a7cfca08e1b94e966ee77c63b11 
and inputs and reference numpy from:
```py
import numpy as np

lhs = np.random.randint(64 ,size=(128, 256))
rhs = np.random.randint(64 ,size=(256, 128))
ref = np.dot(lhs, rhs)

np.save("lhs_i8.npy", lhs.astype(np.int8))
np.save("rhs_i8.npy", rhs.astype(np.int8))
np.save("ref.npy", ref)
```

**Comment by stellaraccident** [comment]
Nice. Can someone merge this with the quant branch above and get a perf readout?

**Comment by antiagainst** [comment]
Stan's change in the above gets us mfma intrinsics. To properly wire up and enable in the model we additionally need to teach MMA deduction logic to see through the fused extsi op. Something like [this one](https://github.com/iree-org/iree/commit/a51511f120c3071165dc954529a154fd35729900).

Also need to add some correctness tests in the [e2e matmul](https://github.com/iree-org/iree/blob/c1cfbfc/tests/e2e/matmul/generate_e2e_matmul_tests.py#L259).

**Comment by kuhar** [comment]
> ```python
> np.save("ref.npy", ref)
> ```

This contains the same bug that I made -- when you save the golden output, the default data type is int64 instead of int32. This should be `np.save("ref.npy", ref.asdtype(np.int32)` to produce bit-identical results with the correct output from `iree-run-module`.

**Comment by kuhar** [comment]
PR: https://github.com/iree-org/iree/pull/17764

**Comment by antiagainst** [comment]
Closing given the above PR is merged.
